name: unsl_erisk_2021
channels:
  - pytorch
  - defaults
dependencies:
  - gensim=3.8
  - numpy=1.18.1
  - pandas=1.0.3
  - python=3.7
  - cudatoolkit=10.1
  - scikit-learn=0.22
  - pytorch
  - pip
  - pip:
    - pyss3
